config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :pages do
    get "turbo"
  end

  root to: "pages#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US" class="text-gray-900 antialiased">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= t("title") %></title>

  <%= stylesheet_pack_tag "application" %>

  <script type="text/javascript">
    window.I18n = {
      defaultLocale : <%== I18n.default_locale.to_json %>,
      locale        : <%== I18n.locale.to_json %>
    };
  </script>
  <%= javascript_pack_tag "application" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<main class="container w-3/4 my-8 mx-auto text-center">
  <header>
    <h1 class="text-4xl text-black"><%= t("title") %></h1>
  </header>

  <%= turbo_frame_tag "description", src: pages_turbo_path do %>
    <%= t(".description") %>
  <% end %>
</main>

app/views/pages/turbo.html.erb
<%= turbo_frame_tag "description" do %>
  <p data-controller="stimulus"><%= t(".description") %></p>
<% end %>